#K-Nearest Neighbour in python using scikit Learn-Symbolic


In [1]:
!pip install scikit-learn
!pip install numpy


In [4]:
#importing Libraries
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing


In [5]:
#loading Dataset
#Oulook,Temperature,Humidity,Windy,Play
dataset = np.array([
                    
['overcast','hot','high','FALSE','yes'],
['overcast','cool','normal','TRUE','yes'],
['overcast','mild','high','TRUE','yes'],
['overcast','hot','normal','FALSE','yes'],
['rainy','mild','high','FALSE','yes'],
['rainy','cool','normal','FALSE','yes'],
['rainy','cool','normal','TRUE','no'],
['rainy','mild','normal','FALSE','yes'],
['rainy','mild','high','TRUE','no'],
['sunny','hot','high','FALSE','no'],
['sunny','hot','high','TRUE','no'],
['sunny','mild','high','FALSE','no'],
['sunny','cool','normal','FALSE','yes'],
['sunny','mild','normal','TRUE','yes']               
])

In [8]:
Features=dataset[:,0:-1]
print(Features)

[['overcast' 'hot' 'high' 'FALSE']
 ['overcast' 'cool' 'normal' 'TRUE']
 ['overcast' 'mild' 'high' 'TRUE']
 ['overcast' 'hot' 'normal' 'FALSE']
 ['rainy' 'mild' 'high' 'FALSE']
 ['rainy' 'cool' 'normal' 'FALSE']
 ['rainy' 'cool' 'normal' 'TRUE']
 ['rainy' 'mild' 'normal' 'FALSE']
 ['rainy' 'mild' 'high' 'TRUE']
 ['sunny' 'hot' 'high' 'FALSE']
 ['sunny' 'hot' 'high' 'TRUE']
 ['sunny' 'mild' 'high' 'FALSE']
 ['sunny' 'cool' 'normal' 'FALSE']
 ['sunny' 'mild' 'normal' 'TRUE']]


In [10]:
enc=preprocessing.OrdinalEncoder()
enc.fit(Features)
features=enc.transform(Features)

In [11]:
print(features)

[[0. 1. 0. 0.]
 [0. 0. 1. 1.]
 [0. 2. 0. 1.]
 [0. 1. 1. 0.]
 [1. 2. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 1.]
 [1. 2. 1. 0.]
 [1. 2. 0. 1.]
 [2. 1. 0. 0.]
 [2. 1. 0. 1.]
 [2. 2. 0. 0.]
 [2. 0. 1. 0.]
 [2. 2. 1. 1.]]


In [12]:
target=dataset[:,-1]
print(target)

['yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'no' 'no' 'yes'
 'yes']


In [16]:
model = KNeighborsClassifier(n_neighbors=3,metric="hamming")
model.fit(features,target)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='hamming',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [63]:
#guess
newday=np.array([["sunny","mild","high","TRUE"]])

In [64]:
prediction = model.predict(enc.transform(newday))

In [65]:
print(prediction)

['no']
